spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/todoapp
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.servlet.session.cookie.same-site=strict
server.servlet.session.cookie.http-only=true
