spring.application.name=backend


spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}


server.port=${PORT:8080}


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/todoapp}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.servlet.session.cookie.same-site=strict
server.servlet.session.cookie.http-only=true
